### ISSUE TITLE
Add Visual Studio 2013 support?

### ISSUE THREAD

**Issue by tankorsmash** [effolkronium/random#11]
This is a _long_ shot, so please don't hesitate to close without discussing too much, but what would be the chances this could be back-ported to Visual Studio 2013?

I tried to hack it together myself, but I'm not familiar with constexpr enough to understand what it should be doing in the first place.

**Comment by effolkronium** [comment]
Well, some important features don't exists in 2013, but I'll try to take a look if there is not too hard way to do it

**Comment by effolkronium** [comment]
Well well well, it seems like there is too big number of errors and issues.
https://ci.appveyor.com/project/effolkronium/random/branch/vs2013

If you want, you can fix them all and create PL for vs2013 branch

BUT! The branch was developed for at least C++11 full support compiler.

I'm believe that there is many ways to rewrite my code and make it works with 2013, but for me it is too big job for some legacy compiler support. That's why i assume it support only in seperate branch.

https://github.com/effolkronium/random/tree/vs2013

Speaking simpler, the motivation to make it works with 2013 is much less then its benefit for me
So, you can take the oars in your own hands and make it works if you really want it :)

**Comment by tankorsmash** [comment]
Thanks for trying it out all the same, I appreciate it! I had also given it a shot but got stumped on a few things. 

If I ever get a PR going, I'll let you know. Thanks again!

**Comment by effolkronium** [comment]
Don't afraid to ask questions or make some intermediate commits into PL or fork. I'd like to help if the job will going on

**Comment by effolkronium** [comment]
resolution: C++11 compilers only :P

**Comment by tankorsmash** [comment]
Yeah, it's a shame VS2013's C++11 support is missing constexpr and some other smaller stuff, it's a pain. Thanks for trying it out!
